name: Publish

on:
    push:
        tags:
            - v*.*.*

permissions:
    contents: write

jobs:
    publish:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin
                    architecture: x64
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: buildPlugin
            -   name: Release
                uses: softprops/action-gh-release@v1
                if: startsWith(github.ref, 'refs/tags/')
                with:
                    name: idea-codelf-plugin ${{ github.ref_name }}
                    files: build/distributions/idea-codelf-plugin-*.zip
                    body_path: changelog/${{ github.ref_name }}.md
