name: Release

on:
    push:
        tags:
            - v*.*.*

permissions:
    contents: write

jobs:
    release:
        runs-on: windows-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin
                    architecture: x64
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Build with Gradle
                run: ./gradlew.bat buildPlugin
            -   name: Release
                uses: softprops/action-gh-release@v2
                if: github.ref_type == 'tag'
                with:
                    name: ${{ github.ref_name }}
                    files: build/distributions/idea-codelf-plugin-*.zip
